# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717d20be2daab7eaf47cad4e0b870824c2afc9f37f615c44a9e4e948df20092efcd86f5a86c39b0e823b22bea2c80a3db4203f960a7a8387fb3662ee7b76c644

test:
  secret_key_base: ff08ab7d60a7709ff734f88c44bbc829742cbb153b92e9076400a01bbdf6b101f7e83ecb9f2ddee499dbe3e7868de99ba43b64ff3a39a4c7792d30843d98fb1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
